# Generated by Django 4.0.5 on 2022-06-13 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('start_time', models.DurationField()),
                ('duration', models.DurationField()),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='wordsearch.episode')),
                ('speaker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='wordsearch.speaker')),
            ],
        ),
    ]
