# Generated by Django 4.0.5 on 2022-06-13 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordsearch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='episode_number',
            new_name='number',
        ),
    ]
