# Generated by Django 4.0.5 on 2023-02-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordsearch', '0007_speaker_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='gender',
            field=models.CharField(max_length=12),
        ),
    ]
