# Generated by Django 4.0.5 on 2023-02-16 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordsearch', '0008_alter_speaker_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speakshare',
            name='speaker',
        ),
        migrations.RemoveField(
            model_name='speakshare',
            name='word_number',
        ),
        migrations.AlterField(
            model_name='speaker',
            name='gender',
            field=models.CharField(default='unknown', max_length=12),
        ),
    ]
