# Generated by Django 4.0.5 on 2023-02-16 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordsearch', '0009_remove_speakshare_speaker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='age',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
