# Generated by Django 4.0.5 on 2023-02-16 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordsearch', '0010_speaker_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='gender',
            field=models.BooleanField(default=None),
        ),
    ]
