# Generated by Django 4.0.5 on 2023-02-16 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordsearch', '0011_alter_speaker_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='gender',
            field=models.CharField(default='unknown', max_length=12),
        ),
    ]
