# Generated by Django 4.0.5 on 2023-03-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordsearch', '0013_episode_duration_episode_spoken_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='duration',
            field=models.DurationField(default=0),
        ),
    ]
