# Generated by Django 4.0.5 on 2023-03-27 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordsearch', '0014_alter_episode_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='duration',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AlterField(
            model_name='episode',
            name='spoken_time',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AlterField(
            model_name='episode',
            name='spoken_words',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
