# Generated by Django 4.0.5 on 2023-04-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordsearch', '0015_alter_episode_duration_alter_episode_spoken_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='words',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
