# Generated by Django 4.2.4 on 2023-08-31 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordsearch', '0016_line_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
